// TODO: Include packages needed for this application
const inquirer = require('inquirer');
const generateMarkdown = require('./utils/generateMarkdown');
const fs = require('fs');

// TODO: Create an array of questions for user input
const questions = [
    {
        type: 'input',
        name: 'title',
        message: 'What is the name of your project? (Required)',
        validate: nameInput => {
          if (nameInput) {
            return true;
          } else {
            console.log('You need to enter a project name!');
            return false;
          }
        }
    },
    {
        type: 'input',
        name: 'description',
        message: 'Please describe your project. (Required)',
        validate: nameInput => {
          if (nameInput) {
            return true;
          } else {
            console.log('You need to enter a desciption!');
            return false;
          }
        }
    },
    {
        type: 'input',
        name: 'tableOfContents',
        message: 'Please write out the sections of your README if applicable.',
    },
    {
        type: 'input',
        name: 'installation',
        message: 'What are the steps required to install your project? Provide a step-by-step description of how to get the development environment running. (Required)',
        validate: nameInput => {
          if (nameInput) {
            return true;
          } else {
            console.log('You need to enter the installation requirements!');
            return false;
          }
        }
    },
    {
        type: 'input',
        name: 'usage',
        message: 'Provide instructions and examples for use. (Required)',
        validate: nameInput => {
          if (nameInput) {
            return true;
          } else {
            console.log('You need to enter how to properly use the application!');
            return false;
          }
        }
    },
    {
        type: 'checkbox',
        name: 'license',
        message: 'What license does this project have?',
        choices: ['Apache', 'GNU', 'MIT', 'Other']
    },
    {
        type: 'input',
        name: 'contributing',
        message: 'If you created an application or package and would like other developers to contribute it, add guidelines for how to do so:',
    },
    {
        type: 'input',
        name: 'tests',
        message: 'Provide test instructions for your application. Then provide examples on how to run them.',
    },
    {
        type: 'input',
        name: 'questions',
        message: 'What is your Github username and email address?',
        validate: nameInput => {
            if (nameInput) {
              return true;
            } else {
              console.log('You need to enter your username and email!');
              return false;
            }
          }
    },
    {
        type: 'input',
        name: 'link',
        message: 'Please provide a link to your video showcasing how to use this application:',
        validate: nameInput => {
            if (nameInput) {
              return true;
            } else {
              console.log('You need to provide a link!');
              return false;
            }
          }
    },
];

// TODO: Create a function to write README file
function writeToFile(fileName, data) {
    fs.writeFile(fileName, data, err => {
        if (err) {
          console.error(err)
          return
        }
        console.log('file written successfully')
      })
}

// TODO: Create a function to initialize app
function init() {inquirer.prompt(questions).then(response => {
    // call write file and pass the answers generated by the markdown function
    writeToFile("./dist/README.md", generateMarkdown(response))
}

)}


// Function call to initialize app
init();
